### ISSUE TITLE
E: Unable to locate package connectd

### ISSUE THREAD

**Issue by bbsuh** [remoteit/docs#10]
I was following the instructions on [Install remote.it connectd](https://docs.remote.it/getting-started/quick-start-on-raspberry-pi/install-remote.it), but the package isn't found.

```
root@zzzzz:~# apt-get update
Hit:1 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
Hit:2 http://fuzon.co.uk/meveric all InRelease
Hit:6 http://fuzon.co.uk/meveric stretch InRelease
Hit:9 http://dev2day.de/pms stretch InRelease
Hit:3 https://oph.mdrjr.net/meveric all InRelease
Ign:4 https://cdn-aws.deb.debian.org/debian stretch InRelease
Hit:5 https://cdn-aws.deb.debian.org/debian stretch-updates InRelease
Hit:7 https://cdn-aws.deb.debian.org/debian-security stretch/updates InRelease
Hit:8 https://cdn-aws.deb.debian.org/debian stretch-backports InRelease
Hit:10 https://cdn-aws.deb.debian.org/debian stretch Release
Reading package lists... Done
root@zzzzz:~# apt-get install connectd
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package connectd
```

Any thoughts?

**Comment by danawoodman** [comment]
Hey @bbsuh, sounds like you got help from Support on this? I will mark as closed but also post here for others:

> apt-get install connectd will only work on Raspbian Stretch as the Pi Foundation has been nice enough to include our package in their repository.
> 
> For other Debian-based Pi releases, please use:
> 
> ```
> wget https://github.com/remoteit/installer/releases/download/v2.2.3.24/connectd_2.2.3.24_armhf.deb
> sudo dpkg -i connectd_2.2.3.24_armhf.deb
> ```
> 
> After that you can use `connecctd_installer` as described here:
> 
> <https://docs.remote.it/using-the-interactive-installer>

**Comment by MichaIng** [comment]
Ah okay that explains some confusion I had as well. Would be good to ask the Pi Foundation to add it as well to the Buster/testing repo. Confusing that it is available in Stretch/stable only, somehow the wrong direction when adding new packages 😄.
