### ISSUE TITLE
`sudo apt install remoteit` returns unable to find package remoteit

### ISSUE THREAD

**Issue by AbnirHencazs** [remoteit/docs#20]
when trying to install remoteit package on my raspberry Pi with Raspbian v8 (JESSIE) i followed the instructions given in the documentation. First, i used `sudo apt update` and then i tried `sudo apt install remoteit` but CLI returns unable to find package remoteit. I aslo have tried with other package names such as connectd and weavedconnectd but still wont find those either.

**Comment by Digital-Larry** [comment]
Please see:

https://support.remote.it/hc/en-us/articles/360047665772-Installing-remoteit-on-older-Raspbian-and-other-Debian-based-operating-systems-for-Raspberry-Pi

**Comment by AbnirHencazs** [comment]
Hi, i followed instructions posted on: https://github.com/remoteit/installer and it worked. Thank you for responding.
